-- =============================================================================
-- Oracle Library Schema — Execution Context
-- =============================================================================
-- Prerequisites:
--   * Must be run as SYS (or a user with DBA privileges).
--   * Must be executed inside a CDB, targeting the XEPDB1 PDB.
--   * Recommended invocation (from host shell):
--       sqlplus / as sysdba @database/oracle_schema.sql
-- =============================================================================

SET DEFINE ON
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET CONTAINER = XEPDB1;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM dba_users
    WHERE username = 'BIBLIOTECA';

    -- Replace &biblioteca_password with your chosen password before executing.
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER BIBLIOTECA IDENTIFIED BY "&biblioteca_password" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
        DBMS_OUTPUT.PUT_LINE('Created user BIBLIOTECA.');
    ELSE
        EXECUTE IMMEDIATE 'ALTER USER BIBLIOTECA IDENTIFIED BY "&biblioteca_password" ACCOUNT UNLOCK';
        EXECUTE IMMEDIATE 'ALTER USER BIBLIOTECA QUOTA UNLIMITED ON USERS';
        DBMS_OUTPUT.PUT_LINE('Updated existing user BIBLIOTECA.');
    END IF;
END;
/

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE VIEW, CREATE PROCEDURE TO BIBLIOTECA;

DECLARE
    PROCEDURE create_table_if_missing(p_table_name IN VARCHAR2, p_sql IN VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM all_tables
        WHERE owner = 'BIBLIOTECA'
          AND table_name = p_table_name;

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('Created table BIBLIOTECA.' || p_table_name || '.');
        ELSE
            DBMS_OUTPUT.PUT_LINE('Table BIBLIOTECA.' || p_table_name || ' already exists; skipped.');
        END IF;
    END;
BEGIN
    create_table_if_missing('ROLES', q'[
        CREATE TABLE BIBLIOTECA.roles (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR2(30) NOT NULL UNIQUE,
            description VARCHAR2(255),
            created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
        )
    ]');

    create_table_if_missing('LIBRARY_USERS', q'[
        CREATE TABLE BIBLIOTECA.library_users (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR2(50) NOT NULL UNIQUE,
            full_name VARCHAR2(120) NOT NULL,
            email VARCHAR2(255) NOT NULL UNIQUE,
            phone VARCHAR2(30),
            password_hash VARCHAR2(255) NOT NULL,
            is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N')),
            role_id NUMBER NOT NULL REFERENCES BIBLIOTECA.roles(id),
            created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
        )
    ]');

    create_table_if_missing('CATEGORIES', q'[
        CREATE TABLE BIBLIOTECA.categories (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR2(80) NOT NULL UNIQUE,
            description VARCHAR2(500),
            is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N')),
            created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
        )
    ]');

    create_table_if_missing('AUTHORS', q'[
        CREATE TABLE BIBLIOTECA.authors (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            first_name VARCHAR2(80) NOT NULL,
            last_name VARCHAR2(80) NOT NULL,
            biography VARCHAR2(2000),
            birth_date DATE,
            death_date DATE,
            is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N')),
            created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT ck_authors_dates CHECK (death_date IS NULL OR birth_date IS NULL OR death_date >= birth_date)
        )
    ]');

    create_table_if_missing('BOOKS', q'[
        CREATE TABLE BIBLIOTECA.books (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR2(200) NOT NULL,
            isbn VARCHAR2(20) UNIQUE,
            description VARCHAR2(4000),
            publication_date DATE,
            publisher VARCHAR2(120),
            edition VARCHAR2(40),
            pages NUMBER CHECK (pages IS NULL OR pages > 0),
            stock_total NUMBER DEFAULT 0 NOT NULL CHECK (stock_total >= 0),
            stock_available NUMBER DEFAULT 0 NOT NULL CHECK (stock_available >= 0),
            is_active CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_active IN ('Y', 'N')),
            category_id NUMBER REFERENCES BIBLIOTECA.categories(id),
            created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT ck_books_stock CHECK (stock_available <= stock_total)
        )
    ]');

    create_table_if_missing('BOOK_AUTHORS', q'[
        CREATE TABLE BIBLIOTECA.book_authors (
            book_id NUMBER NOT NULL REFERENCES BIBLIOTECA.books(id) ON DELETE CASCADE,
            author_id NUMBER NOT NULL REFERENCES BIBLIOTECA.authors(id) ON DELETE CASCADE,
            created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT pk_book_authors PRIMARY KEY (book_id, author_id)
        )
    ]');

    create_table_if_missing('LOANS', q'[
        CREATE TABLE BIBLIOTECA.loans (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id NUMBER NOT NULL REFERENCES BIBLIOTECA.library_users(id),
            book_id NUMBER NOT NULL REFERENCES BIBLIOTECA.books(id),
            loan_date DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
            due_date DATE NOT NULL,
            return_date DATE,
            status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'RETURNED', 'OVERDUE', 'CANCELLED')),
            created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT ck_loans_due_date CHECK (due_date >= loan_date),
            CONSTRAINT ck_loans_return_date CHECK (return_date IS NULL OR return_date >= loan_date)
        )
    ]');

    create_table_if_missing('RETURNS', q'[
        CREATE TABLE BIBLIOTECA.returns (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            loan_id NUMBER NOT NULL UNIQUE REFERENCES BIBLIOTECA.loans(id),
            return_date DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
            fine_amount NUMBER(10, 2) DEFAULT 0 NOT NULL CHECK (fine_amount >= 0),
            notes VARCHAR2(1000),
            created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
        )
    ]');
END;
/

CREATE OR REPLACE TRIGGER BIBLIOTECA.trg_roles_updated_at
BEFORE UPDATE ON BIBLIOTECA.roles
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER BIBLIOTECA.trg_library_users_updated_at
BEFORE UPDATE ON BIBLIOTECA.library_users
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER BIBLIOTECA.trg_categories_updated_at
BEFORE UPDATE ON BIBLIOTECA.categories
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER BIBLIOTECA.trg_authors_updated_at
BEFORE UPDATE ON BIBLIOTECA.authors
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER BIBLIOTECA.trg_books_updated_at
BEFORE UPDATE ON BIBLIOTECA.books
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER BIBLIOTECA.trg_loans_updated_at
BEFORE UPDATE ON BIBLIOTECA.loans
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER BIBLIOTECA.trg_returns_updated_at
BEFORE UPDATE ON BIBLIOTECA.returns
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER BIBLIOTECA.trg_loans_checkout_stock
BEFORE INSERT ON BIBLIOTECA.loans
FOR EACH ROW
DECLARE
    v_stock_available NUMBER;
BEGIN
    IF :NEW.status IS NULL THEN
        :NEW.status := 'ACTIVE';
    END IF;

    IF :NEW.status = 'ACTIVE' THEN
        SELECT stock_available
        INTO v_stock_available
        FROM BIBLIOTECA.books
        WHERE id = :NEW.book_id
        FOR UPDATE;

        IF v_stock_available <= 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Book has no available stock for loan.');
        END IF;

        UPDATE BIBLIOTECA.books
        SET stock_available = stock_available - 1
        WHERE id = :NEW.book_id;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BIBLIOTECA.trg_returns_restore_stock
AFTER INSERT ON BIBLIOTECA.returns
FOR EACH ROW
DECLARE
    v_book_id BIBLIOTECA.loans.book_id%TYPE;
    v_status BIBLIOTECA.loans.status%TYPE;
BEGIN
    SELECT book_id, status
    INTO v_book_id, v_status
    FROM BIBLIOTECA.loans
    WHERE id = :NEW.loan_id
    FOR UPDATE;

    IF v_status <> 'RETURNED' THEN
        UPDATE BIBLIOTECA.loans
        SET status = 'RETURNED',
            return_date = :NEW.return_date
        WHERE id = :NEW.loan_id;

        UPDATE BIBLIOTECA.books
        SET stock_available = CASE
            WHEN stock_available < stock_total THEN stock_available + 1
            ELSE stock_available
        END
        WHERE id = v_book_id;
    END IF;
END;
/

DECLARE
    PROCEDURE create_index_if_missing(p_index_name IN VARCHAR2, p_sql IN VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM all_indexes
        WHERE owner = 'BIBLIOTECA'
          AND index_name = p_index_name;

        IF v_count = 0 THEN
            BEGIN
                EXECUTE IMMEDIATE p_sql;
                DBMS_OUTPUT.PUT_LINE('Created index BIBLIOTECA.' || p_index_name || '.');
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE = -1408 THEN
                        DBMS_OUTPUT.PUT_LINE('Index columns for BIBLIOTECA.' || p_index_name || ' are already indexed; skipped.');
                    ELSE
                        RAISE;
                    END IF;
            END;
        ELSE
            DBMS_OUTPUT.PUT_LINE('Index BIBLIOTECA.' || p_index_name || ' already exists; skipped.');
        END IF;
    END;
BEGIN
    create_index_if_missing('IX_BOOKS_TITLE', 'CREATE INDEX BIBLIOTECA.ix_books_title ON BIBLIOTECA.books(title)');
    create_index_if_missing('IX_BOOKS_CATEGORY', 'CREATE INDEX BIBLIOTECA.ix_books_category ON BIBLIOTECA.books(category_id)');
    create_index_if_missing('IX_AUTHORS_NAME', 'CREATE INDEX BIBLIOTECA.ix_authors_name ON BIBLIOTECA.authors(last_name, first_name)');
    create_index_if_missing('IX_USERS_ROLE', 'CREATE INDEX BIBLIOTECA.ix_users_role ON BIBLIOTECA.library_users(role_id)');
    create_index_if_missing('IX_LOANS_USER_STATUS', 'CREATE INDEX BIBLIOTECA.ix_loans_user_status ON BIBLIOTECA.loans(user_id, status)');
    create_index_if_missing('IX_LOANS_BOOK_STATUS', 'CREATE INDEX BIBLIOTECA.ix_loans_book_status ON BIBLIOTECA.loans(book_id, status)');
    create_index_if_missing('IX_RETURNS_LOAN', 'CREATE INDEX BIBLIOTECA.ix_returns_loan ON BIBLIOTECA.returns(loan_id)');
END;
/

MERGE INTO BIBLIOTECA.roles target
USING (
    SELECT 'Admin' AS name, 'System administrator role.' AS description FROM dual
    UNION ALL
    SELECT 'Usuario' AS name, 'Default library user role.' AS description FROM dual
) source
ON (target.name = source.name)
WHEN NOT MATCHED THEN
    INSERT (name, description)
    VALUES (source.name, source.description);

COMMIT;

PROMPT BIBLIOTECA Oracle schema is ready in XEPDB1.
EXIT
